from __future__ import annotations

from agentx_evolve.recovery.failure_models import (
    ACTION_RETRY,
    ACTION_REBUILD_CONTEXT,
    ACTION_ROLLBACK,
    ACTION_BLOCK_SESSION,
    ACTION_ENTER_SAFE_MODE,
    ACTION_REQUEST_HUMAN_REVIEW,
    ACTION_REJECT_OUTPUT,
    ACTION_REVALIDATE,
    ACTION_NO_ACTION,
)

REQUIRED_RULE_IDS: list[str] = [
    "REC-POL-001-MODEL-INVALID-OUTPUT",
    "REC-POL-002-MODEL-INSUFFICIENT-CONTEXT",
    "REC-POL-003-PATCH-APPLY-FAILED",
    "REC-POL-004-VALIDATION-FAILED",
    "REC-POL-005-GOVERNANCE-BLOCKED",
    "REC-POL-006-RISK-TOO-HIGH",
    "REC-POL-007-SOURCE-GUARD-FAILED",
    "REC-POL-008-ROLLBACK-FAILED",
    "REC-POL-009-SCHEMA-VALIDATION-FAILED",
    "REC-POL-010-TOOL-FAILURE",
    "REC-POL-011-LOCK-CONFLICT",
    "REC-POL-012-ATOMIC-WRITE-FAILED",
    "REC-POL-013-PROMPT-CONTRACT-FAILED",
    "REC-POL-014-POLICY-DENIED",
    "REC-POL-015-SANDBOX-CRITICAL",
    "REC-POL-016-SECRET-REDACTION-FAILED",
    "REC-POL-017-UNKNOWN-FAILURE",
]

ALL_RECOVERY_ACTIONS: set[str] = {
    ACTION_RETRY,
    ACTION_REBUILD_CONTEXT,
    ACTION_ROLLBACK,
    ACTION_BLOCK_SESSION,
    ACTION_ENTER_SAFE_MODE,
    ACTION_REQUEST_HUMAN_REVIEW,
    ACTION_REJECT_OUTPUT,
    ACTION_REVALIDATE,
    ACTION_NO_ACTION,
}

FAILURE_TO_RULE_MAP: dict[str, str] = {
    "MODEL_INVALID_OUTPUT": "REC-POL-001-MODEL-INVALID-OUTPUT",
    "MODEL_INSUFFICIENT_CONTEXT": "REC-POL-002-MODEL-INSUFFICIENT-CONTEXT",
    "PATCH_APPLY_FAILED": "REC-POL-003-PATCH-APPLY-FAILED",
    "VALIDATION_FAILED": "REC-POL-004-VALIDATION-FAILED",
    "GOVERNANCE_BLOCKED": "REC-POL-005-GOVERNANCE-BLOCKED",
    "RISK_TOO_HIGH": "REC-POL-006-RISK-TOO-HIGH",
    "SOURCE_GUARD_FAILED": "REC-POL-007-SOURCE-GUARD-FAILED",
    "ROLLBACK_FAILED": "REC-POL-008-ROLLBACK-FAILED",
    "SCHEMA_VALIDATION_FAILED": "REC-POL-009-SCHEMA-VALIDATION-FAILED",
    "TOOL_FAILURE": "REC-POL-010-TOOL-FAILURE",
    "LOCK_CONFLICT": "REC-POL-011-LOCK-CONFLICT",
    "ATOMIC_WRITE_FAILED": "REC-POL-012-ATOMIC-WRITE-FAILED",
    "PROMPT_CONTRACT_FAILED": "REC-POL-013-PROMPT-CONTRACT-FAILED",
    "POLICY_DENIED": "REC-POL-014-POLICY-DENIED",
    "PATH_TRAVERSAL": "REC-POL-015-SANDBOX-CRITICAL",
    "PATH_OUTSIDE_REPO": "REC-POL-015-SANDBOX-CRITICAL",
    "SYMLINK_ESCAPE": "REC-POL-015-SANDBOX-CRITICAL",
    "L0_WRITE_BLOCKED": "REC-POL-015-SANDBOX-CRITICAL",
    "PROTECTED_PATH_BLOCKED": "REC-POL-015-SANDBOX-CRITICAL",
    "SECRET_REDACTION_FAILED": "REC-POL-016-SECRET-REDACTION-FAILED",
    "UNKNOWN_FAILURE": "REC-POL-017-UNKNOWN-FAILURE",
    "CAPABILITY_MISSING": "REC-POL-014-POLICY-DENIED",
    "ROLE_NOT_AUTHORIZED": "REC-POL-014-POLICY-DENIED",
    "TOOL_NOT_ALLOWED": "REC-POL-010-TOOL-FAILURE",
    "MODEL_NOT_ALLOWED": "REC-POL-010-TOOL-FAILURE",
    "PATH_NOT_ALLOWED": "REC-POL-014-POLICY-DENIED",
    "NETWORK_MODE_DENIED": "REC-POL-014-POLICY-DENIED",
    "APPROVAL_REQUIRED": "REC-POL-014-POLICY-DENIED",
    "SOURCE_WRITE_DISABLED": "REC-POL-015-SANDBOX-CRITICAL",
    "RUNTIME_WRITE_BOUNDARY_VIOLATION": "REC-POL-015-SANDBOX-CRITICAL",
    "SUBPROCESS_BLOCKED": "REC-POL-015-SANDBOX-CRITICAL",
    "COMMAND_NOT_ALLOWLISTED": "REC-POL-015-SANDBOX-CRITICAL",
    "NETWORK_BLOCKED": "REC-POL-015-SANDBOX-CRITICAL",
    "UNEXPECTED_FILE_MUTATION": "REC-POL-015-SANDBOX-CRITICAL",
    "IMPLEMENTATION_SESSION_FAILED": "REC-POL-003-PATCH-APPLY-FAILED",
}


def get_recovery_rule_for_failure(failure_class: str) -> dict:
    rule_id = FAILURE_TO_RULE_MAP.get(failure_class, "REC-POL-017-UNKNOWN-FAILURE")
    return {
        "rule_id": rule_id,
        "failure_class": failure_class,
        "actions": _get_default_actions_for_rule(rule_id),
    }


def get_allowed_recovery_actions() -> set[str]:
    return set(ALL_RECOVERY_ACTIONS)


def _get_default_actions_for_rule(rule_id: str) -> list[str]:
    rule_map = {
        "REC-POL-001-MODEL-INVALID-OUTPUT": [ACTION_REJECT_OUTPUT, ACTION_RETRY],
        "REC-POL-002-MODEL-INSUFFICIENT-CONTEXT": [ACTION_REBUILD_CONTEXT],
        "REC-POL-003-PATCH-APPLY-FAILED": [ACTION_ROLLBACK, ACTION_BLOCK_SESSION],
        "REC-POL-004-VALIDATION-FAILED": [ACTION_REVALIDATE, ACTION_ROLLBACK],
        "REC-POL-005-GOVERNANCE-BLOCKED": [ACTION_BLOCK_SESSION],
        "REC-POL-006-RISK-TOO-HIGH": [ACTION_REQUEST_HUMAN_REVIEW, ACTION_BLOCK_SESSION],
        "REC-POL-007-SOURCE-GUARD-FAILED": [ACTION_ROLLBACK, ACTION_ENTER_SAFE_MODE, ACTION_REQUEST_HUMAN_REVIEW],
        "REC-POL-008-ROLLBACK-FAILED": [ACTION_ENTER_SAFE_MODE, ACTION_REQUEST_HUMAN_REVIEW],
        "REC-POL-009-SCHEMA-VALIDATION-FAILED": [ACTION_REJECT_OUTPUT, ACTION_BLOCK_SESSION],
        "REC-POL-010-TOOL-FAILURE": [ACTION_RETRY, ACTION_BLOCK_SESSION],
        "REC-POL-011-LOCK-CONFLICT": [ACTION_BLOCK_SESSION],
        "REC-POL-012-ATOMIC-WRITE-FAILED": [ACTION_BLOCK_SESSION, ACTION_REQUEST_HUMAN_REVIEW],
        "REC-POL-013-PROMPT-CONTRACT-FAILED": [ACTION_REJECT_OUTPUT],
        "REC-POL-014-POLICY-DENIED": [ACTION_BLOCK_SESSION],
        "REC-POL-015-SANDBOX-CRITICAL": [ACTION_ENTER_SAFE_MODE, ACTION_REQUEST_HUMAN_REVIEW],
        "REC-POL-016-SECRET-REDACTION-FAILED": [ACTION_BLOCK_SESSION, ACTION_REQUEST_HUMAN_REVIEW],
        "REC-POL-017-UNKNOWN-FAILURE": [ACTION_REQUEST_HUMAN_REVIEW, ACTION_BLOCK_SESSION],
    }
    return rule_map.get(rule_id, [ACTION_BLOCK_SESSION])
