from .acceptance_models import (
    ALL_MODES, MODE_IMPLEMENTATION_ACCEPTANCE, MODE_SOURCE_ONLY_ACCEPTANCE,
    MODE_NON_PRODUCTION_ACCEPTANCE, MODE_PRODUCTION_ACCEPTANCE, MODE_RELEASE_ACCEPTANCE,
    FinalAcceptanceModePolicy,
)

_MODE_REQUIRED_RULES: dict[str, set[str]] = {
    MODE_IMPLEMENTATION_ACCEPTANCE: {
        "L0_SEED_KERNEL", "L1_STANDARDS_FRAMEWORK", "L2_PROFILES_DOCS",
        "AGENTX_INITIATOR", "SECURITY_SANDBOX", "POLICY_CAPABILITY_REGISTRY",
        "FAILURE_TAXONOMY", "TOOL_MCP_ADAPTER", "EVALUATION_HARNESS",
        "FINAL_SYSTEM_ACCEPTANCE",
    },
    MODE_SOURCE_ONLY_ACCEPTANCE: {
        "L0_SEED_KERNEL", "L1_STANDARDS_FRAMEWORK", "L2_PROFILES_DOCS",
        "AGENTX_INITIATOR", "SECURITY_SANDBOX", "POLICY_CAPABILITY_REGISTRY",
        "FAILURE_TAXONOMY", "TOOL_MCP_ADAPTER", "EVALUATION_HARNESS",
        "FINAL_SYSTEM_ACCEPTANCE",
    },
    MODE_NON_PRODUCTION_ACCEPTANCE: {
        "L0_SEED_KERNEL", "L1_STANDARDS_FRAMEWORK", "L2_PROFILES_DOCS",
        "AGENTX_INITIATOR", "SECURITY_SANDBOX", "POLICY_CAPABILITY_REGISTRY",
        "GOVERNED_PATCH_EXECUTION", "FAILURE_TAXONOMY", "TOOL_MCP_ADAPTER",
        "MODEL_ADAPTER", "LOCAL_MODEL_RUNTIME_PROFILE", "CONTEXT_BUILDER_TASK_PACKER",
        "PROMPT_CONTRACT_VERSIONING", "LLM_IMPLEMENTATION_WORKER",
        "SELF_EVOLUTION_ORCHESTRATOR", "HUMAN_REVIEW_APPROVAL",
        "PROMOTION_RELEASE_GATE", "GIT_INTEGRATION", "EVALUATION_HARNESS",
        "LONG_TERM_LEARNING", "DOCUMENTATION_SYNC", "TASK_QUEUE_SESSION_SCHEDULER",
        "FINAL_SYSTEM_ACCEPTANCE",
    },
    MODE_PRODUCTION_ACCEPTANCE: {
        "L0_SEED_KERNEL", "L1_STANDARDS_FRAMEWORK", "L2_PROFILES_DOCS",
        "AGENTX_INITIATOR", "SECURITY_SANDBOX", "POLICY_CAPABILITY_REGISTRY",
        "GOVERNED_PATCH_EXECUTION", "FAILURE_TAXONOMY", "TOOL_MCP_ADAPTER",
        "MODEL_ADAPTER", "LOCAL_MODEL_RUNTIME_PROFILE", "CONTEXT_BUILDER_TASK_PACKER",
        "PROMPT_CONTRACT_VERSIONING", "LLM_IMPLEMENTATION_WORKER",
        "SELF_EVOLUTION_ORCHESTRATOR", "HUMAN_REVIEW_APPROVAL",
        "PROMOTION_RELEASE_GATE", "GIT_INTEGRATION", "EVALUATION_HARNESS",
        "LONG_TERM_LEARNING", "DOCUMENTATION_SYNC", "TASK_QUEUE_SESSION_SCHEDULER",
        "MONITORING_OBSERVABILITY", "BACKUP_DISASTER_RECOVERY",
        "FINAL_SYSTEM_ACCEPTANCE",
    },
    MODE_RELEASE_ACCEPTANCE: {
        "L0_SEED_KERNEL", "L1_STANDARDS_FRAMEWORK", "L2_PROFILES_DOCS",
        "AGENTX_INITIATOR", "SECURITY_SANDBOX", "POLICY_CAPABILITY_REGISTRY",
        "GOVERNED_PATCH_EXECUTION", "FAILURE_TAXONOMY", "TOOL_MCP_ADAPTER",
        "MODEL_ADAPTER", "LOCAL_MODEL_RUNTIME_PROFILE", "CONTEXT_BUILDER_TASK_PACKER",
        "PROMPT_CONTRACT_VERSIONING", "LLM_IMPLEMENTATION_WORKER",
        "SELF_EVOLUTION_ORCHESTRATOR", "HUMAN_REVIEW_APPROVAL",
        "PROMOTION_RELEASE_GATE", "GIT_INTEGRATION", "EVALUATION_HARNESS",
        "LONG_TERM_LEARNING", "DOCUMENTATION_SYNC", "TASK_QUEUE_SESSION_SCHEDULER",
        "MONITORING_OBSERVABILITY", "PACKAGING_DISTRIBUTION", "BACKUP_DISASTER_RECOVERY",
        "FINAL_SYSTEM_ACCEPTANCE",
    },
}

_MODE_DEFERRAL_ALLOWED: dict[str, set[str]] = {
    MODE_IMPLEMENTATION_ACCEPTANCE: set(),
    MODE_SOURCE_ONLY_ACCEPTANCE: {
        "GOVERNED_PATCH_EXECUTION", "MODEL_ADAPTER", "LOCAL_MODEL_RUNTIME_PROFILE",
        "CONTEXT_BUILDER_TASK_PACKER", "PROMPT_CONTRACT_VERSIONING",
        "LLM_IMPLEMENTATION_WORKER", "SELF_EVOLUTION_ORCHESTRATOR",
        "HUMAN_REVIEW_APPROVAL", "PROMOTION_RELEASE_GATE", "GIT_INTEGRATION",
        "LONG_TERM_LEARNING", "DOCUMENTATION_SYNC", "TASK_QUEUE_SESSION_SCHEDULER",
        "MONITORING_OBSERVABILITY", "PACKAGING_DISTRIBUTION", "BACKUP_DISASTER_RECOVERY",
    },
    MODE_NON_PRODUCTION_ACCEPTANCE: {
        "LONG_TERM_LEARNING", "TASK_QUEUE_SESSION_SCHEDULER",
        "MONITORING_OBSERVABILITY", "BACKUP_DISASTER_RECOVERY",
    },
    MODE_PRODUCTION_ACCEPTANCE: {
        "LONG_TERM_LEARNING", "TASK_QUEUE_SESSION_SCHEDULER",
    },
    MODE_RELEASE_ACCEPTANCE: {
        "LONG_TERM_LEARNING", "TASK_QUEUE_SESSION_SCHEDULER",
    },
}


def build_mode_policy(mode: str) -> dict:
    return {
        "schema_version": "1.0",
        "schema_id": "final_acceptance_mode_policy.schema.json",
        "source_component": "AGENTX_FINAL_SYSTEM_ACCEPTANCE",
        "acceptance_mode": mode,
        "required_layers": sorted(_MODE_REQUIRED_RULES.get(mode, set())),
        "deferral_allowed_layers": sorted(_MODE_DEFERRAL_ALLOWED.get(mode, set())),
        "warnings": [],
        "errors": [],
    }


def _mode_policy_obj(mode: str) -> FinalAcceptanceModePolicy:
    return FinalAcceptanceModePolicy(
        acceptance_mode=mode,
        mode_rules=build_mode_policy(mode),
    )


def is_layer_required_for_mode(layer_id: str, mode: str) -> bool:
    required = _MODE_REQUIRED_RULES.get(mode, set())
    return layer_id in required


def is_deferral_allowed_for_mode(layer_id: str, mode: str) -> bool:
    allowed = _MODE_DEFERRAL_ALLOWED.get(mode, set())
    if layer_id in allowed:
        return True
    return not is_layer_required_for_mode(layer_id, mode)


def validate_acceptance_mode(mode: str) -> list[str]:
    errors: list[str] = []
    if mode not in ALL_MODES:
        errors.append(
            f"Invalid acceptance mode '{mode}'. "
            f"Must be one of: {', '.join(sorted(ALL_MODES))}"
        )
    return errors
