from agentx_evolve.orchestrator.orchestrator_config import (
    ORCH_STATUS_CREATED,
    ORCH_STATUS_PLANNING,
    ORCH_STATUS_PLAN_READY,
    ORCH_STATUS_WAITING_FOR_APPROVAL,
    ORCH_STATUS_RUNNING,
    ORCH_STATUS_STEP_BLOCKED,
    ORCH_STATUS_STEP_FAILED,
    ORCH_STATUS_RECOVERING,
    ORCH_STATUS_VALIDATING,
    ORCH_STATUS_READY_FOR_PROMOTION,
    ORCH_STATUS_PROMOTION_BLOCKED,
    ORCH_STATUS_COMPLETED,
    ORCH_STATUS_FAILED,
    ORCH_STATUS_ABORTED,
    ORCH_ALL_STATUSES,
    ORCH_TERMINAL_STATUSES,
    ORCH_TRANSITIONS,
    SESSION_STATUS_ACTIVE,
    SESSION_STATUS_PAUSED,
    SESSION_STATUS_BLOCKED,
    SESSION_STATUS_COMPLETED,
    SESSION_STATUS_FAILED,
    SESSION_STATUS_CANCELLED,
    ALL_SESSION_STATUSES,
    STEP_STATUS_PENDING,
    STEP_STATUS_READY,
    STEP_STATUS_RUNNING,
    STEP_STATUS_BLOCKED,
    STEP_STATUS_FAILED,
    STEP_STATUS_SKIPPED,
    STEP_STATUS_COMPLETED,
    STEP_STATUS_NEEDS_APPROVAL,
    STEP_STATUS_NEEDS_GOVERNANCE,
    ALL_STEP_STATUSES,
    DECISION_CONTINUE,
    DECISION_BLOCK,
    DECISION_RETRY,
    DECISION_RECOVER,
    DECISION_REQUIRE_APPROVAL,
    DECISION_REQUIRE_GOVERNANCE,
    DECISION_ABORT,
    DECISION_READY_FOR_PROMOTION,
    DECISION_COMPLETE,
    DECISION_NOT_DONE,
    ALL_DECISIONS,
    RUN_MODE_PLAN_ONLY,
    RUN_MODE_DRY_RUN,
    RUN_MODE_EXECUTE_CONTROLLED,
    RUN_MODE_RESUME,
    RUN_MODE_VALIDATE_ONLY,
    RUN_MODE_REVIEW_ONLY,
    ALL_RUN_MODES,
    DEPENDENCY_MODE_REAL,
    DEPENDENCY_MODE_FAKE_FOR_TEST,
    DEPENDENCY_MODE_RESTRICTED,
    DEPENDENCY_MODE_UNAVAILABLE,
    ALL_DEPENDENCY_MODES,
    RECOVERY_ACTION_NONE,
    RECOVERY_ACTION_RETRY,
    RECOVERY_ACTION_REPLAN,
    RECOVERY_ACTION_ROLLBACK_REQUEST,
    RECOVERY_ACTION_HUMAN_REVIEW,
    RECOVERY_ACTION_STOP_RUN,
    ALL_RECOVERY_ACTIONS,
    GATE_TYPE_APPROVAL,
    GATE_TYPE_GOVERNANCE,
    GATE_TYPE_PROMOTION,
    ALL_GATE_TYPES,
    GATE_STATUS_PENDING,
    GATE_STATUS_APPROVED,
    GATE_STATUS_DENIED,
    GATE_STATUS_ABSTAIN,
    GATE_STATUS_NOT_REQUIRED,
    ALL_GATE_STATUSES,
    STAGE_TYPE_TOOL,
    STAGE_TYPE_MODEL,
    STAGE_TYPE_POLICY,
    STAGE_TYPE_GATE,
    STAGE_TYPE_RECOVERY,
    STAGE_TYPE_EVIDENCE,
    STAGE_TYPE_LOCKING,
    STAGE_TYPE_PLANNING,
    STAGE_TYPE_PROMOTION,
    ALL_STAGE_TYPES,
    RISK_LEVEL_LOW,
    RISK_LEVEL_MEDIUM,
    RISK_LEVEL_HIGH,
    RISK_LEVEL_CRITICAL,
    ALL_RISK_LEVELS,
    RUNTIME_ARTIFACT_ROOT,
    DEFAULT_MAX_STEPS,
    DEFAULT_MAX_RETRIES_TOTAL,
    DEFAULT_MAX_RETRIES_PER_STEP,
    DEFAULT_MAX_TOOL_CALLS,
    DEFAULT_MAX_MODEL_CALLS,
    DEFAULT_MAX_RUN_SECONDS,
    DEFAULT_MAX_STEP_SECONDS,
    DEFAULT_MAX_EVIDENCE_BYTES,
    DEFAULT_MAX_REPLANS,
    COMPONENT_ID,
    COMPONENT_NAME,
    ROADMAP_LAYER,
    ROADMAP_PHASE,
    SCHEMA_VERSION,
    SOURCE_COMPONENT,
)

import pytest


class TestOrchestratorConfig:
    def test_orch_statuses_defined(self):
        assert ORCH_STATUS_CREATED == "CREATED"
        assert ORCH_STATUS_PLANNING == "PLANNING"
        assert ORCH_STATUS_PLAN_READY == "PLAN_READY"
        assert ORCH_STATUS_WAITING_FOR_APPROVAL == "WAITING_FOR_APPROVAL"
        assert ORCH_STATUS_RUNNING == "RUNNING"
        assert ORCH_STATUS_STEP_BLOCKED == "STEP_BLOCKED"
        assert ORCH_STATUS_STEP_FAILED == "STEP_FAILED"
        assert ORCH_STATUS_RECOVERING == "RECOVERING"
        assert ORCH_STATUS_VALIDATING == "VALIDATING"
        assert ORCH_STATUS_READY_FOR_PROMOTION == "READY_FOR_PROMOTION"
        assert ORCH_STATUS_PROMOTION_BLOCKED == "PROMOTION_BLOCKED"
        assert ORCH_STATUS_COMPLETED == "COMPLETED"
        assert ORCH_STATUS_FAILED == "FAILED"
        assert ORCH_STATUS_ABORTED == "ABORTED"

    def test_orch_all_statuses_has_14(self):
        assert len(ORCH_ALL_STATUSES) == 14

    def test_orch_terminal_statuses(self):
        assert ORCH_STATUS_COMPLETED in ORCH_TERMINAL_STATUSES
        assert ORCH_STATUS_FAILED in ORCH_TERMINAL_STATUSES
        assert ORCH_STATUS_ABORTED in ORCH_TERMINAL_STATUSES

    def test_transitions_exist(self):
        assert ORCH_STATUS_CREATED in ORCH_TRANSITIONS
        assert ORCH_STATUS_PLANNING in ORCH_TRANSITIONS[ORCH_STATUS_CREATED]
        assert ORCH_STATUS_VALIDATING in ORCH_TRANSITIONS[ORCH_STATUS_RUNNING]
        assert ORCH_STATUS_COMPLETED in ORCH_TRANSITIONS[ORCH_STATUS_READY_FOR_PROMOTION]

    def test_session_statuses(self):
        assert SESSION_STATUS_ACTIVE == "ACTIVE"
        assert SESSION_STATUS_FAILED == "FAILED"
        assert SESSION_STATUS_CANCELLED == "CANCELLED"
        assert len(ALL_SESSION_STATUSES) == 6

    def test_step_statuses(self):
        assert STEP_STATUS_PENDING == "PENDING"
        assert STEP_STATUS_BLOCKED == "BLOCKED"
        assert STEP_STATUS_COMPLETED == "COMPLETED"
        assert len(ALL_STEP_STATUSES) == 9

    def test_decisions(self):
        assert DECISION_CONTINUE == "CONTINUE"
        assert DECISION_BLOCK == "BLOCK"
        assert DECISION_COMPLETE == "COMPLETE"
        assert DECISION_NOT_DONE == "NOT_DONE"
        assert len(ALL_DECISIONS) == 10

    def test_run_modes(self):
        assert RUN_MODE_PLAN_ONLY == "PLAN_ONLY"
        assert RUN_MODE_EXECUTE_CONTROLLED == "EXECUTE_CONTROLLED"
        assert len(ALL_RUN_MODES) == 6

    def test_dependency_modes(self):
        assert DEPENDENCY_MODE_REAL == "REAL"
        assert DEPENDENCY_MODE_FAKE_FOR_TEST == "FAKE_FOR_TEST"
        assert DEPENDENCY_MODE_RESTRICTED == "RESTRICTED"
        assert DEPENDENCY_MODE_UNAVAILABLE == "UNAVAILABLE"
        assert len(ALL_DEPENDENCY_MODES) == 4

    def test_recovery_actions(self):
        assert RECOVERY_ACTION_NONE == "NONE"
        assert RECOVERY_ACTION_RETRY == "RETRY"
        assert RECOVERY_ACTION_STOP_RUN == "STOP_RUN"
        assert RECOVERY_ACTION_HUMAN_REVIEW == "HUMAN_REVIEW"
        assert len(ALL_RECOVERY_ACTIONS) == 6

    def test_gate_types(self):
        assert GATE_TYPE_APPROVAL == "APPROVAL"
        assert GATE_TYPE_GOVERNANCE == "GOVERNANCE"
        assert GATE_TYPE_PROMOTION == "PROMOTION"
        assert len(ALL_GATE_TYPES) == 3

    def test_gate_statuses(self):
        assert GATE_STATUS_PENDING == "PENDING"
        assert GATE_STATUS_APPROVED == "APPROVED"
        assert GATE_STATUS_DENIED == "DENIED"
        assert GATE_STATUS_ABSTAIN == "ABSTAIN"
        assert GATE_STATUS_NOT_REQUIRED == "NOT_REQUIRED"
        assert len(ALL_GATE_STATUSES) == 5

    def test_stage_types(self):
        assert STAGE_TYPE_TOOL == "TOOL"
        assert STAGE_TYPE_MODEL == "MODEL"
        assert STAGE_TYPE_PROMOTION == "PROMOTION"
        assert len(ALL_STAGE_TYPES) == 9

    def test_risk_levels(self):
        assert RISK_LEVEL_LOW == "low"
        assert RISK_LEVEL_CRITICAL == "critical"
        assert len(ALL_RISK_LEVELS) == 4

    def test_default_budgets(self):
        assert DEFAULT_MAX_STEPS == 50
        assert DEFAULT_MAX_RETRIES_TOTAL == 3
        assert DEFAULT_MAX_TOOL_CALLS == 100
        assert DEFAULT_MAX_MODEL_CALLS == 20

    def test_component_constants(self):
        assert COMPONENT_ID == "AGENTX_SELF_EVOLUTION_ORCHESTRATOR"
        assert isinstance(COMPONENT_NAME, str)
        assert isinstance(ROADMAP_LAYER, int)
        assert isinstance(SCHEMA_VERSION, str)
        assert isinstance(SOURCE_COMPONENT, str)
