from .policy_models import (
    PolicyRule, CapabilityDefinition, ToolCapability, CapabilityRegistry,
    PolicyEnforcementResult, SideEffectLevel,
    RULE_ALLOW, RULE_DENY, RULE_REQUIRE_APPROVAL,
    ENFORCEMENT_ALLOW, ENFORCEMENT_BLOCK, ENFORCEMENT_REQUIRE_APPROVAL,
    SIDE_EFFECT_READ, SIDE_EFFECT_WRITE, SIDE_EFFECT_DESTRUCTIVE,
    OP_READ, OP_WRITE, OP_EDIT, OP_DELETE, OP_EXECUTE, OP_NETWORK, OP_SUBPROCESS,
)
from .capability_registry import CapabilityRegistryImpl, EngineCapabilityRegistry, CapabilityRegistryError
from .policy_enforcer import PolicyEnforcer
from .policy_loader import PolicyLoader

# ── Policy / Capability Registry (spec v5) exports ───────────────────────────

from .policy_models import (
    ALL_ROLES,
    CapabilityEntry,
    CapabilityPolicy,
    DECISION_ALLOW,
    DECISION_BLOCK,
    DECISION_INVALID_POLICY,
    DECISION_NEEDS_APPROVAL,
    DECISION_NEEDS_GOVERNANCE,
    DECISION_NEEDS_RISK_REVIEW,
    DECISION_NEEDS_SANDBOX_CHECK,
    DECISION_NEEDS_VALIDATION,
    DECISION_UNKNOWN_MODEL,
    DECISION_UNKNOWN_ROLE,
    DECISION_UNKNOWN_TOOL,
    DECISION_WARN,
    EFFECT_AUDIT_WRITE,
    EFFECT_EDIT_SOURCE,
    EFFECT_EXECUTE_COMMAND,
    EFFECT_GRAPH_WRITE,
    EFFECT_MEMORY_WRITE,
    EFFECT_PATCH_APPLY,
    EFFECT_PATCH_PRECHECK,
    EFFECT_PROMOTE,
    EFFECT_READ,
    EFFECT_READ_GIT,
    EFFECT_REQUEST_APPROVAL,
    EFFECT_ROLLBACK,
    EFFECT_USE_MODEL,
    EFFECT_USE_NETWORK,
    EFFECT_WRITE_GIT,
    EFFECT_WRITE_RUNTIME,
    EFFECT_WRITE_SOURCE,
    ModelPolicy,
    ModelProfile,
    NON_OVERRIDABLE_BLOCKS,
    PolicyAudit,
    PolicyDecision,
    PolicyViolation,
    ROLE_HUMAN_OPERATOR,
    ROLE_IMPLEMENTATION_WORKER,
    ROLE_MODEL_ADAPTER,
    ROLE_ORCHESTRATOR,
    ROLE_PATCH_EXECUTOR,
    ROLE_PROMOTION_CHECKER,
    ROLE_REVIEWER_ASSISTANT,
    ROLE_TOOL_ADAPTER,
    ROLE_VALIDATION_REPAIR_WORKER,
    RolePermissionMatrix,
    ToolEntry,
    ToolPolicy,
    TRUST_TIER_0_READ_ONLY,
    TRUST_TIER_1_LOCAL_STATE_WRITE,
    TRUST_TIER_2_APPROVED_SOURCE_WRITE,
    TRUST_TIER_3_VALIDATION_EXECUTION,
    TRUST_TIER_4_GIT_WRITE,
    TRUST_TIER_5_NETWORK_OR_EXTERNAL,
    TRUST_TIER_6_BLOCKED,
    REASON_ALLOW_BY_CAPABILITY,
    REASON_DEFAULT_BLOCK,
    REASON_UNKNOWN_ROLE,
    REASON_UNKNOWN_TOOL,
    REASON_UNKNOWN_EFFECT,
    REASON_UNKNOWN_MODEL,
    REASON_INVALID_POLICY,
    REASON_TOOL_BLOCKED,
    REASON_TOOL_EFFECT_NOT_ALLOWED,
    REASON_CAPABILITY_MISSING,
    REASON_CAPABILITY_EFFECT_BLOCKED,
    REASON_REQUIRES_APPROVAL,
    REASON_REQUIRES_GOVERNANCE,
    REASON_REQUIRES_SANDBOX,
    REASON_REQUIRES_RISK_REVIEW,
    REASON_REQUIRES_VALIDATION,
    REASON_NETWORK_BLOCKED_BY_DEFAULT,
    REASON_HOSTED_MODEL_BLOCKED_BY_DEFAULT,
    REASON_MODEL_CANNOT_WRITE_FILES,
    REASON_MODEL_CANNOT_EXECUTE_COMMANDS,
    REASON_MODEL_CANNOT_EXECUTE_TOOLS,
    REASON_GIT_WRITE_BLOCKED_BY_DEFAULT,
    REASON_HUMAN_CANNOT_OVERRIDE_HARD_BLOCK,
    REASON_SANDBOX_BLOCK_IS_AUTHORITATIVE,
)
from .policy_defaults import (
    load_default_capability_policy,
    load_default_model_policy,
    load_default_role_permission_matrix,
    load_default_role_permission_matrix as load_default_role_matrix,
    load_default_tool_policy,
)
from .role_matrix import (
    build_default_role_permission_matrix,
    check_role_permission,
    get_role_default_decision,
    get_role_permissions,
    is_non_overridable_block,
    is_valid_role,
    role_exists,
)
from .capability_policy import (
    capability_requires_approval,
    capability_requires_governance,
    capability_requires_sandbox,
    find_capability,
    is_effect_allowed,
    is_effect_blocked,
)
from .tool_policy import (
    find_tool,
    tool_allows_effect,
    tool_exists,
    tool_executes_command,
    tool_is_blocked,
    tool_requires_governance,
    tool_requires_human_approval,
    tool_requires_sandbox,
    tool_uses_network,
    tool_writes_source,
)
from .model_policy import (
    find_model_profile,
    model_may_execute_commands,
    model_may_execute_tools,
    model_may_read_source,
    model_may_use_network,
    model_may_write_files,
    model_profile_exists,
    model_task_allowed,
)
from .policy_decision import (
    check_policy_allowed,
    check_role_permission as check_role_permission_pd,
    choose_strictest_decision,
    evaluate_model_request,
    evaluate_tool_request,
)
from .policy_registry import PolicyRegistry
from .policy_evidence import (
    append_policy_decision,
    append_policy_violation,
    build_policy_audit_event,
    write_latest_policy_decision,
    write_policy_decision,
)
from .initiator_policy_compat import InitiatorPolicyCompat, get_policy_registry
