from __future__ import annotations

SCHEMA_VERSION = "1.0"
SOURCE_COMPONENT = "SelfEvolutionOrchestrator"

ORCH_STATUS_CREATED = "CREATED"
ORCH_STATUS_PLANNING = "PLANNING"
ORCH_STATUS_PLAN_READY = "PLAN_READY"
ORCH_STATUS_WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
ORCH_STATUS_RUNNING = "RUNNING"
ORCH_STATUS_STEP_BLOCKED = "STEP_BLOCKED"
ORCH_STATUS_STEP_FAILED = "STEP_FAILED"
ORCH_STATUS_RECOVERING = "RECOVERING"
ORCH_STATUS_VALIDATING = "VALIDATING"
ORCH_STATUS_READY_FOR_PROMOTION = "READY_FOR_PROMOTION"
ORCH_STATUS_PROMOTION_BLOCKED = "PROMOTION_BLOCKED"
ORCH_STATUS_COMPLETED = "COMPLETED"
ORCH_STATUS_FAILED = "FAILED"
ORCH_STATUS_ABORTED = "ABORTED"

ORCH_ALL_STATUSES = [
    ORCH_STATUS_CREATED,
    ORCH_STATUS_PLANNING,
    ORCH_STATUS_PLAN_READY,
    ORCH_STATUS_WAITING_FOR_APPROVAL,
    ORCH_STATUS_RUNNING,
    ORCH_STATUS_STEP_BLOCKED,
    ORCH_STATUS_STEP_FAILED,
    ORCH_STATUS_RECOVERING,
    ORCH_STATUS_VALIDATING,
    ORCH_STATUS_READY_FOR_PROMOTION,
    ORCH_STATUS_PROMOTION_BLOCKED,
    ORCH_STATUS_COMPLETED,
    ORCH_STATUS_FAILED,
    ORCH_STATUS_ABORTED,
]

ORCH_TERMINAL_STATUSES = {
    ORCH_STATUS_COMPLETED,
    ORCH_STATUS_FAILED,
    ORCH_STATUS_ABORTED,
}

ORCH_TRANSITIONS: dict[str, list[str]] = {
    ORCH_STATUS_CREATED: [ORCH_STATUS_PLANNING],
    ORCH_STATUS_PLANNING: [ORCH_STATUS_PLAN_READY, ORCH_STATUS_FAILED],
    ORCH_STATUS_PLAN_READY: [ORCH_STATUS_WAITING_FOR_APPROVAL, ORCH_STATUS_RUNNING],
    ORCH_STATUS_WAITING_FOR_APPROVAL: [ORCH_STATUS_RUNNING, ORCH_STATUS_ABORTED],
    ORCH_STATUS_RUNNING: [ORCH_STATUS_STEP_BLOCKED, ORCH_STATUS_STEP_FAILED, ORCH_STATUS_VALIDATING],
    ORCH_STATUS_STEP_BLOCKED: [ORCH_STATUS_WAITING_FOR_APPROVAL, ORCH_STATUS_ABORTED],
    ORCH_STATUS_STEP_FAILED: [ORCH_STATUS_RECOVERING, ORCH_STATUS_FAILED],
    ORCH_STATUS_RECOVERING: [ORCH_STATUS_RUNNING, ORCH_STATUS_FAILED],
    ORCH_STATUS_VALIDATING: [ORCH_STATUS_READY_FOR_PROMOTION, ORCH_STATUS_FAILED],
    ORCH_STATUS_READY_FOR_PROMOTION: [ORCH_STATUS_COMPLETED, ORCH_STATUS_PROMOTION_BLOCKED],
    ORCH_STATUS_PROMOTION_BLOCKED: [ORCH_STATUS_ABORTED],
    ORCH_STATUS_COMPLETED: [],
    ORCH_STATUS_FAILED: [],
    ORCH_STATUS_ABORTED: [],
}

SESSION_STATUS_ACTIVE = "ACTIVE"
SESSION_STATUS_PAUSED = "PAUSED"
SESSION_STATUS_BLOCKED = "BLOCKED"
SESSION_STATUS_COMPLETED = "COMPLETED"
SESSION_STATUS_FAILED = "FAILED"
SESSION_STATUS_CANCELLED = "CANCELLED"

ALL_SESSION_STATUSES = [
    SESSION_STATUS_ACTIVE,
    SESSION_STATUS_PAUSED,
    SESSION_STATUS_BLOCKED,
    SESSION_STATUS_COMPLETED,
    SESSION_STATUS_FAILED,
    SESSION_STATUS_CANCELLED,
]

STEP_STATUS_PENDING = "PENDING"
STEP_STATUS_READY = "READY"
STEP_STATUS_RUNNING = "RUNNING"
STEP_STATUS_BLOCKED = "BLOCKED"
STEP_STATUS_FAILED = "FAILED"
STEP_STATUS_SKIPPED = "SKIPPED"
STEP_STATUS_COMPLETED = "COMPLETED"
STEP_STATUS_NEEDS_APPROVAL = "NEEDS_APPROVAL"
STEP_STATUS_NEEDS_GOVERNANCE = "NEEDS_GOVERNANCE"

ALL_STEP_STATUSES = [
    STEP_STATUS_PENDING,
    STEP_STATUS_READY,
    STEP_STATUS_RUNNING,
    STEP_STATUS_BLOCKED,
    STEP_STATUS_FAILED,
    STEP_STATUS_SKIPPED,
    STEP_STATUS_COMPLETED,
    STEP_STATUS_NEEDS_APPROVAL,
    STEP_STATUS_NEEDS_GOVERNANCE,
]

DECISION_CONTINUE = "CONTINUE"
DECISION_BLOCK = "BLOCK"
DECISION_RETRY = "RETRY"
DECISION_RECOVER = "RECOVER"
DECISION_REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
DECISION_REQUIRE_GOVERNANCE = "REQUIRE_GOVERNANCE"
DECISION_ABORT = "ABORT"
DECISION_READY_FOR_PROMOTION = "READY_FOR_PROMOTION"
DECISION_COMPLETE = "COMPLETE"
DECISION_NOT_DONE = "NOT_DONE"

ALL_DECISIONS = [
    DECISION_CONTINUE,
    DECISION_BLOCK,
    DECISION_RETRY,
    DECISION_RECOVER,
    DECISION_REQUIRE_APPROVAL,
    DECISION_REQUIRE_GOVERNANCE,
    DECISION_ABORT,
    DECISION_READY_FOR_PROMOTION,
    DECISION_COMPLETE,
    DECISION_NOT_DONE,
]

RUN_MODE_PLAN_ONLY = "PLAN_ONLY"
RUN_MODE_DRY_RUN = "DRY_RUN"
RUN_MODE_EXECUTE_CONTROLLED = "EXECUTE_CONTROLLED"
RUN_MODE_RESUME = "RESUME"
RUN_MODE_VALIDATE_ONLY = "VALIDATE_ONLY"
RUN_MODE_REVIEW_ONLY = "REVIEW_ONLY"

ALL_RUN_MODES = [
    RUN_MODE_PLAN_ONLY,
    RUN_MODE_DRY_RUN,
    RUN_MODE_EXECUTE_CONTROLLED,
    RUN_MODE_RESUME,
    RUN_MODE_VALIDATE_ONLY,
    RUN_MODE_REVIEW_ONLY,
]

DEPENDENCY_MODE_REAL = "REAL"
DEPENDENCY_MODE_RESTRICTED = "RESTRICTED"
DEPENDENCY_MODE_UNAVAILABLE = "UNAVAILABLE"

ALL_DEPENDENCY_MODES = [
    DEPENDENCY_MODE_REAL,
    DEPENDENCY_MODE_RESTRICTED,
    DEPENDENCY_MODE_UNAVAILABLE,
]

RECOVERY_ACTION_NONE = "NONE"
RECOVERY_ACTION_RETRY = "RETRY"
RECOVERY_ACTION_REPLAN = "REPLAN"
RECOVERY_ACTION_ROLLBACK_REQUEST = "ROLLBACK_REQUEST"
RECOVERY_ACTION_HUMAN_REVIEW = "HUMAN_REVIEW"
RECOVERY_ACTION_STOP_RUN = "STOP_RUN"

ALL_RECOVERY_ACTIONS = [
    RECOVERY_ACTION_NONE,
    RECOVERY_ACTION_RETRY,
    RECOVERY_ACTION_REPLAN,
    RECOVERY_ACTION_ROLLBACK_REQUEST,
    RECOVERY_ACTION_HUMAN_REVIEW,
    RECOVERY_ACTION_STOP_RUN,
]

GATE_TYPE_APPROVAL = "APPROVAL"
GATE_TYPE_GOVERNANCE = "GOVERNANCE"
GATE_TYPE_PROMOTION = "PROMOTION"

ALL_GATE_TYPES = [
    GATE_TYPE_APPROVAL,
    GATE_TYPE_GOVERNANCE,
    GATE_TYPE_PROMOTION,
]

GATE_STATUS_PENDING = "PENDING"
GATE_STATUS_APPROVED = "APPROVED"
GATE_STATUS_DENIED = "DENIED"
GATE_STATUS_ABSTAIN = "ABSTAIN"
GATE_STATUS_NOT_REQUIRED = "NOT_REQUIRED"

ALL_GATE_STATUSES = [
    GATE_STATUS_PENDING,
    GATE_STATUS_APPROVED,
    GATE_STATUS_DENIED,
    GATE_STATUS_ABSTAIN,
    GATE_STATUS_NOT_REQUIRED,
]

STAGE_TYPE_TOOL = "TOOL"
STAGE_TYPE_MODEL = "MODEL"
STAGE_TYPE_POLICY = "POLICY"
STAGE_TYPE_GATE = "GATE"
STAGE_TYPE_RECOVERY = "RECOVERY"
STAGE_TYPE_EVIDENCE = "EVIDENCE"
STAGE_TYPE_LOCKING = "LOCKING"
STAGE_TYPE_PLANNING = "PLANNING"
STAGE_TYPE_PROMOTION = "PROMOTION"

ALL_STAGE_TYPES = [
    STAGE_TYPE_TOOL,
    STAGE_TYPE_MODEL,
    STAGE_TYPE_POLICY,
    STAGE_TYPE_GATE,
    STAGE_TYPE_RECOVERY,
    STAGE_TYPE_EVIDENCE,
    STAGE_TYPE_LOCKING,
    STAGE_TYPE_PLANNING,
    STAGE_TYPE_PROMOTION,
]

RISK_LEVEL_LOW = "low"
RISK_LEVEL_MEDIUM = "medium"
RISK_LEVEL_HIGH = "high"
RISK_LEVEL_CRITICAL = "critical"

ALL_RISK_LEVELS = [
    RISK_LEVEL_LOW,
    RISK_LEVEL_MEDIUM,
    RISK_LEVEL_HIGH,
    RISK_LEVEL_CRITICAL,
]

RUNTIME_ARTIFACT_ROOT = ".agentx-init/orchestrator"

DEFAULT_MAX_STEPS = 50
DEFAULT_MAX_RETRIES_TOTAL = 3
DEFAULT_MAX_RETRIES_PER_STEP = 1
DEFAULT_MAX_TOOL_CALLS = 100
DEFAULT_MAX_MODEL_CALLS = 20
DEFAULT_MAX_RUN_SECONDS = 1800
DEFAULT_MAX_STEP_SECONDS = 300
DEFAULT_MAX_EVIDENCE_BYTES = 50 * 1024 * 1024
DEFAULT_MAX_REPLANS = 1

COMPONENT_ID = "AGENTX_SELF_EVOLUTION_ORCHESTRATOR"
COMPONENT_NAME = "Self-Evolution Orchestrator"
ROADMAP_LAYER = 11
ROADMAP_PHASE = "Phase C"
