from __future__ import annotations

ORCH_RUN_ADMISSION_DENIED = "ORCH_RUN_ADMISSION_DENIED"
ORCH_DEPENDENCY_MISSING = "ORCH_DEPENDENCY_MISSING"
ORCH_CONTRACT_INCOMPATIBLE = "ORCH_CONTRACT_INCOMPATIBLE"
ORCH_INVALID_STATE_TRANSITION = "ORCH_INVALID_STATE_TRANSITION"
ORCH_TERMINAL_STATE_IMMUTABLE = "ORCH_TERMINAL_STATE_IMMUTABLE"
ORCH_GATE_NOT_CHECKED = "ORCH_GATE_NOT_CHECKED"
ORCH_GATE_BLOCKED = "ORCH_GATE_BLOCKED"
ORCH_TOOL_BINDING_INVALID = "ORCH_TOOL_BINDING_INVALID"
ORCH_TOOL_RESULT_MISSING = "ORCH_TOOL_RESULT_MISSING"
ORCH_MODEL_BINDING_INVALID = "ORCH_MODEL_BINDING_INVALID"
ORCH_MODEL_OUTPUT_CONTRACT_VIOLATION = "ORCH_MODEL_OUTPUT_CONTRACT_VIOLATION"
ORCH_PROMPT_CONTRACT_MISSING = "ORCH_PROMPT_CONTRACT_MISSING"
ORCH_POLICY_DENIED = "ORCH_POLICY_DENIED"
ORCH_SANDBOX_DENIED = "ORCH_SANDBOX_DENIED"
ORCH_PATCH_LAYER_DENIED = "ORCH_PATCH_LAYER_DENIED"
ORCH_HUMAN_APPROVAL_MISSING = "ORCH_HUMAN_APPROVAL_MISSING"
ORCH_PROMOTION_DENIED = "ORCH_PROMOTION_DENIED"
ORCH_RETRY_LIMIT_EXCEEDED = "ORCH_RETRY_LIMIT_EXCEEDED"
ORCH_BUDGET_EXCEEDED = "ORCH_BUDGET_EXCEEDED"
ORCH_EVIDENCE_MISSING = "ORCH_EVIDENCE_MISSING"
ORCH_EVIDENCE_HASH_MISMATCH = "ORCH_EVIDENCE_HASH_MISMATCH"
ORCH_REPLAY_MISMATCH = "ORCH_REPLAY_MISMATCH"
ORCH_INTERRUPT_REQUESTED = "ORCH_INTERRUPT_REQUESTED"
ORCH_FAILURE_UNCLASSIFIED = "ORCH_FAILURE_UNCLASSIFIED"
ORCH_APPROVED_PLAN_HASH_MISMATCH = "ORCH_APPROVED_PLAN_HASH_MISMATCH"
ORCH_SIDE_EFFECT_MISMATCH = "ORCH_SIDE_EFFECT_MISMATCH"
ORCH_AUTHORITY_SNAPSHOT_MISSING = "ORCH_AUTHORITY_SNAPSHOT_MISSING"
ORCH_LEDGER_SEQUENCE_INVALID = "ORCH_LEDGER_SEQUENCE_INVALID"
ORCH_EVIDENCE_QUARANTINED = "ORCH_EVIDENCE_QUARANTINED"
ORCH_UNKNOWN_FAILURE = "ORCH_UNKNOWN_FAILURE"

ALL_ORCHESTRATOR_FAILURE_CLASSES = [
    ORCH_RUN_ADMISSION_DENIED,
    ORCH_DEPENDENCY_MISSING,
    ORCH_CONTRACT_INCOMPATIBLE,
    ORCH_INVALID_STATE_TRANSITION,
    ORCH_TERMINAL_STATE_IMMUTABLE,
    ORCH_GATE_NOT_CHECKED,
    ORCH_GATE_BLOCKED,
    ORCH_TOOL_BINDING_INVALID,
    ORCH_TOOL_RESULT_MISSING,
    ORCH_MODEL_BINDING_INVALID,
    ORCH_MODEL_OUTPUT_CONTRACT_VIOLATION,
    ORCH_PROMPT_CONTRACT_MISSING,
    ORCH_POLICY_DENIED,
    ORCH_SANDBOX_DENIED,
    ORCH_PATCH_LAYER_DENIED,
    ORCH_HUMAN_APPROVAL_MISSING,
    ORCH_PROMOTION_DENIED,
    ORCH_RETRY_LIMIT_EXCEEDED,
    ORCH_BUDGET_EXCEEDED,
    ORCH_EVIDENCE_MISSING,
    ORCH_EVIDENCE_HASH_MISMATCH,
    ORCH_REPLAY_MISMATCH,
    ORCH_INTERRUPT_REQUESTED,
    ORCH_FAILURE_UNCLASSIFIED,
    ORCH_APPROVED_PLAN_HASH_MISMATCH,
    ORCH_SIDE_EFFECT_MISMATCH,
    ORCH_AUTHORITY_SNAPSHOT_MISSING,
    ORCH_LEDGER_SEQUENCE_INVALID,
    ORCH_EVIDENCE_QUARANTINED,
    ORCH_UNKNOWN_FAILURE,
]
