from __future__ import annotations

WORKER_SUCCESS = "SUCCESS"
WORKER_PARTIAL = "PARTIAL"
WORKER_BLOCKED = "BLOCKED"
WORKER_FAILED = "FAILED"
WORKER_INVALID = "INVALID"

ALL_WORKER_STATUSES = [
    WORKER_SUCCESS,
    WORKER_PARTIAL,
    WORKER_BLOCKED,
    WORKER_FAILED,
    WORKER_INVALID,
]

MODE_PLAN_ONLY = "PLAN_ONLY"
MODE_PATCH_PROPOSAL = "PATCH_PROPOSAL"
MODE_VALIDATION_HANDOFF = "VALIDATION_HANDOFF"
MODE_REPAIR_PLAN = "REPAIR_PLAN"
MODE_RESTRICTED = "RESTRICTED"

ALL_WORKER_MODES = [
    MODE_PLAN_ONLY,
    MODE_PATCH_PROPOSAL,
    MODE_VALIDATION_HANDOFF,
    MODE_REPAIR_PLAN,
    MODE_RESTRICTED,
]

DEP_AVAILABLE = "AVAILABLE"
DEP_MISSING = "MISSING"
DEP_FAILED = "FAILED"
DEP_NOT_CHECKED = "NOT CHECKED"

ALL_DEPENDENCY_STATUSES = [
    DEP_AVAILABLE,
    DEP_MISSING,
    DEP_FAILED,
    DEP_NOT_CHECKED,
]

PATCH_FORMAT_UNIFIED_DIFF = "unified_diff"
PATCH_FORMAT_STRUCTURED_FILE_CHANGE_LIST = "structured_file_change_list"
PATCH_FORMAT_GOVERNED_PATCH_REQUEST = "governed_patch_request"

ALL_PATCH_FORMATS = [
    PATCH_FORMAT_UNIFIED_DIFF,
    PATCH_FORMAT_STRUCTURED_FILE_CHANGE_LIST,
    PATCH_FORMAT_GOVERNED_PATCH_REQUEST,
]

HANDOFF_STATUS_PENDING = "PENDING"
HANDOFF_STATUS_HANDED_OFF = "HANDED_OFF"
HANDOFF_STATUS_BLOCKED = "BLOCKED"
HANDOFF_STATUS_FAILED = "FAILED"

ALL_HANDOFF_STATUSES = [
    HANDOFF_STATUS_PENDING,
    HANDOFF_STATUS_HANDED_OFF,
    HANDOFF_STATUS_BLOCKED,
    HANDOFF_STATUS_FAILED,
]

MODEL_RESPONSE_STATUS_SUCCESS = "SUCCESS"
MODEL_RESPONSE_STATUS_BLOCKED = "BLOCKED"
MODEL_RESPONSE_STATUS_FAILED = "FAILED"
MODEL_RESPONSE_STATUS_INVALID = "INVALID"
MODEL_RESPONSE_STATUS_OVERSIZED = "OVERSIZED"
MODEL_RESPONSE_STATUS_SECRET_LIKE = "SECRET_LIKE"

ALL_MODEL_RESPONSE_STATUSES = [
    MODEL_RESPONSE_STATUS_SUCCESS,
    MODEL_RESPONSE_STATUS_BLOCKED,
    MODEL_RESPONSE_STATUS_FAILED,
    MODEL_RESPONSE_STATUS_INVALID,
    MODEL_RESPONSE_STATUS_OVERSIZED,
    MODEL_RESPONSE_STATUS_SECRET_LIKE,
]

RUNTIME_ARTIFACT_ROOT = ".agentx-init/implementation_worker"

ALLOWED_VALIDATION_COMMANDS = [
    "compileall",
    "pytest",
    "schema-validation",
    "static-check",
    "typecheck",
]

DEFAULT_MAX_CONTEXT_CHARS = 100000
DEFAULT_MAX_MODEL_OUTPUT_CHARS = 32000
DEFAULT_TEMPERATURE = 0.0
DEFAULT_MODEL_REQUEST_TIMEOUT_SECONDS = 120
DEFAULT_TOOL_REQUEST_TIMEOUT_SECONDS = 60

MAX_RETRY_COUNT = 3
MIN_RETRY_DELAY_SECONDS = 1.0
MAX_RETRY_DELAY_SECONDS = 30.0

SCHEMA_VERSION = "1.0"
SOURCE_COMPONENT = "LLMImplementationWorker"
