from __future__ import annotations

WORKER_TASK_SCHEMA_INVALID = "WORKER_TASK_SCHEMA_INVALID"
WORKER_POLICY_DENIED = "WORKER_POLICY_DENIED"
WORKER_DEPENDENCY_MISSING = "WORKER_DEPENDENCY_MISSING"
WORKER_CONTEXT_BUILD_FAILED = "WORKER_CONTEXT_BUILD_FAILED"
WORKER_CONTEXT_TOO_LARGE = "WORKER_CONTEXT_TOO_LARGE"
WORKER_PROMPT_BUILD_FAILED = "WORKER_PROMPT_BUILD_FAILED"
WORKER_MODEL_POLICY_DENIED = "WORKER_MODEL_POLICY_DENIED"
WORKER_MODEL_CALL_FAILED = "WORKER_MODEL_CALL_FAILED"
WORKER_MODEL_RESPONSE_INVALID = "WORKER_MODEL_RESPONSE_INVALID"
WORKER_MODEL_OUTPUT_REJECTED = "WORKER_MODEL_OUTPUT_REJECTED"
WORKER_PATCH_PROPOSAL_INVALID = "WORKER_PATCH_PROPOSAL_INVALID"
WORKER_VALIDATION_HANDOFF_FAILED = "WORKER_VALIDATION_HANDOFF_FAILED"
WORKER_TOOL_REQUEST_DENIED = "WORKER_TOOL_REQUEST_DENIED"
WORKER_DIRECT_MUTATION_BLOCKED = "WORKER_DIRECT_MUTATION_BLOCKED"
WORKER_EVIDENCE_WRITE_FAILED = "WORKER_EVIDENCE_WRITE_FAILED"
WORKER_UNKNOWN_FAILURE = "WORKER_UNKNOWN_FAILURE"

ALL_WORKER_FAILURE_CLASSES = [
    WORKER_TASK_SCHEMA_INVALID,
    WORKER_POLICY_DENIED,
    WORKER_DEPENDENCY_MISSING,
    WORKER_CONTEXT_BUILD_FAILED,
    WORKER_CONTEXT_TOO_LARGE,
    WORKER_PROMPT_BUILD_FAILED,
    WORKER_MODEL_POLICY_DENIED,
    WORKER_MODEL_CALL_FAILED,
    WORKER_MODEL_RESPONSE_INVALID,
    WORKER_MODEL_OUTPUT_REJECTED,
    WORKER_PATCH_PROPOSAL_INVALID,
    WORKER_VALIDATION_HANDOFF_FAILED,
    WORKER_TOOL_REQUEST_DENIED,
    WORKER_DIRECT_MUTATION_BLOCKED,
    WORKER_EVIDENCE_WRITE_FAILED,
    WORKER_UNKNOWN_FAILURE,
]
