#!/usr/bin/env python3
"""Validates the artifacts generated by generate_enterprise_artifacts.py.

Usage:
    python validate_enterprise_artifacts.py <target>
    python validate_enterprise_artifacts.py --list
"""

import json
import sys
from pathlib import Path

from agentx_evolve.enterprise import (
    ADAPTER_REPORTS,
    API_ABUSE_REPORTS,
    ASSURANCE_REPORTS,
    AUDIT_RETENTION_REPORTS,
    AUTH_REPORTS,
    BUSINESS_STATE_REPORTS,
    CATALOG_REPORTS,
    CONFIG_DRIFT_REPORTS,
    CONNECTOR_REPORTS,
    CONTRACT_REPORTS,
    CONTROL_PLANE_REPORTS,
    CROSS_TENANT_REPORTS,
    CUTOVER_REPORTS,
    DATA_GOV_REPORTS,
    DATA_MIGRATION_REPORTS,
    DURABLE_REPORTS,
    ENTERPRISE_ADOPTION_REPORTS,
    ENTERPRISE_FINAL,
    ENTERPRISE_REPORTS,
    EVALS_REPORTS,
    FAILOVER_REPORTS,
    FINAL_ADOPTION_REPORTS,
    GENERATION_REPORTS,
    IDENTITY_HARDENING_REPORTS,
    KNOWLEDGE_REPORTS,
    LAST_MILE_REPORTS,
    LIVE_CONNECTOR_REPORTS,
    MULTI_AGENT_REPORTS,
    ONBOARDING_REPORTS,
    OPERATOR_USABILITY_REPORTS,
    OPS_REPORTS,
    PACKAGING_REPORTS,
    PERF_REPORTS,
    PROCESS_INT_REPORTS,
    RESIDUAL_RISK_REPORTS,
    RISK_REPORTS,
    RUNTIME_REPORTS,
    SANDBOX_LIVE_REPORTS,
    SECURITY_REVIEW_REPORTS,
    WHOLE_COMPANY_REPORTS,
    WORKFLOW_REPORTS,
    ALL_ENTERPRISE_GATES,
    ALL_ENT_ROWS,
)

VERDICT_MATRIX_TARGETS = frozenset({
    "contract-system", "adapter-sandbox", "workflow-pack", "workflow-runtime",
    "arbitrary-agent-generation", "connector-certification", "agent-catalog",
    "multi-agent", "auth-rbac", "data-governance", "production-ops",
    "domain-evals", "security-review", "control-plane", "durable-workers",
    "process-intake", "risk-policy", "enterprise-knowledge", "packaging",
    "live-connector", "performance-slo", "onboarding", "event-webhook",
    "policy-pack", "assurance-case", "business-state", "failover-drill",
    "sandbox-live-boundary", "whole-company-exemplar", "residual-risk",
    "customer-data-migration", "operator-usability", "identity-hardening",
    "api-abuse", "cross-tenant", "audit-retention", "config-drift",
    "cutover-drill", "sso-idp", "sbom", "segregation-duties",
    "field-record-authz", "backup-restore", "customer-acceptance",
    "data-quality", "training-runbook", "enterprise-ready", "enterprise-final",
})


def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def check_exists(path: Path) -> bool:
    ok = path.exists()
    label = str(path.relative_to(path.anchor) if path.is_absolute() else path)
    if ok:
        print(f"  PASS  {label} exists")
    else:
        print(f"  FAIL  {label} missing")
    return ok


def check_eq(data: dict, key: str, expected: object) -> bool:
    actual = data.get(key)
    ok = actual == expected
    if ok:
        print(f"  PASS  {key} == {expected!r}")
    else:
        print(f"  FAIL  {key} == {actual!r} (expected {expected!r})")
    return ok


def check_has(data: dict, key: str) -> bool:
    ok = key in data
    if ok:
        print(f"  PASS  has key {key!r}")
    else:
        print(f"  FAIL  missing key {key!r}")
    return ok


def check_ge(data: dict, key: str, minimum: int) -> bool:
    actual = data.get(key, -1)
    ok = isinstance(actual, (int, float)) and actual >= minimum
    if ok:
        print(f"  PASS  {key} == {actual} >= {minimum}")
    else:
        print(f"  FAIL  {key} == {actual!r} (expected >= {minimum})")
    return ok


def check_verdict_pass(dir_path: Path, filename: str) -> bool:
    ok = True
    path = dir_path / filename
    if not check_exists(path):
        return False
    data = load_json(path)
    ok &= check_eq(data, "verdict", "PASS")
    return ok


def check_matrix_has_rows(dir_path: Path, filename: str) -> bool:
    ok = True
    path = dir_path / filename
    if not check_exists(path):
        return False
    data = load_json(path)
    ok &= check_has(data, "rows")
    return ok


# ---------------------------------------------------------------------------
# Per-target validators
# ---------------------------------------------------------------------------

def validate_contract_system() -> bool:
    d = CONTRACT_REPORTS
    ok = True
    for f in [
        "contract_system_verdict.json",
        "CONTRACT_SYSTEM_VERDICT.md",
        "contract_acceptance_matrix.json",
        "contract_schema_manifest.json",
        "contract_negative_tests_report.json",
    ]:
        ok &= check_exists(d / f)

    if ok or True:
        v = d / "contract_system_verdict.json"
        if v.exists():
            data = load_json(v)
            ok &= check_eq(data, "classification", "ENTERPRISE_CONTRACT_SYSTEM")
            ok &= check_eq(data, "verdict", "PASS")
            ok &= check_eq(data, "contract_first_agents", "PASS")
            ok &= check_eq(data, "schema_validation", "PASS")
            ok &= check_eq(data, "versioning_and_hashes", "PASS")
            ok &= check_eq(data, "negative_tests", "PASS")
        m = d / "contract_acceptance_matrix.json"
        if m.exists():
            ok &= check_has(load_json(m), "rows")
        n = d / "contract_negative_tests_report.json"
        if n.exists():
            ok &= check_ge(load_json(n), "passed", 0)
    return ok


def validate_adapter_sandbox() -> bool:
    d = ADAPTER_REPORTS
    ok = True
    files = [
        "enterprise_adapter_sandbox_verdict.json",
        "enterprise_adapter_acceptance_matrix.json",
        "enterprise_adapter_replay_report.json",
        "enterprise_adapter_security_report.json",
        "enterprise_adapter_command_transcript.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "enterprise_adapter_sandbox_verdict.json")
    ok &= check_matrix_has_rows(d, "enterprise_adapter_acceptance_matrix.json")
    return ok


def validate_workflow_pack() -> bool:
    d = WORKFLOW_REPORTS
    ok = True
    files = [
        "workflow_pack_verdict.json",
        "workflow_acceptance_matrix.json",
        "workflow_replay_report.json",
        "workflow_negative_tests_report.json",
        "workflow_evidence_manifest.json",
        "workflow_operator_summary.md",
    ]
    for f in files:
        ok &= check_exists(d / f)

    v = d / "workflow_pack_verdict.json"
    if v.exists():
        data = load_json(v)
        ok &= check_ge(data, "packs_that_pass", 6)
        ok &= check_eq(data, "verdict", "PASS")
    ok &= check_matrix_has_rows(d, "workflow_acceptance_matrix.json")
    n = d / "workflow_negative_tests_report.json"
    if n.exists():
        ok &= check_ge(load_json(n), "passed", 0)
    return ok


def validate_workflow_runtime() -> bool:
    d = RUNTIME_REPORTS
    ok = True
    files = [
        "workflow_runtime_verdict.json",
        "workflow_runtime_acceptance_matrix.json",
        "workflow_runtime_replay_report.json",
        "workflow_runtime_failure_injection_report.json",
        "workflow_runtime_compensation_report.json",
        "workflow_runtime_command_transcript.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "workflow_runtime_verdict.json")
    ok &= check_matrix_has_rows(d, "workflow_runtime_acceptance_matrix.json")
    return ok


def validate_arbitrary_agent_generation() -> bool:
    d = GENERATION_REPORTS
    ok = True
    files = [
        "arbitrary_agent_generation_verdict.json",
        "unseen_contract_fixture_manifest.json",
        "generated_agent_manifest.json",
        "generated_agent_acceptance_matrix.json",
        "generated_agent_negative_tests_report.json",
        "generated_agent_replay_report.json",
        "generated_agent_command_transcript.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "arbitrary_agent_generation_verdict.json")
    ok &= check_matrix_has_rows(d, "generated_agent_acceptance_matrix.json")
    return ok


def validate_connector_certification() -> bool:
    d = CONNECTOR_REPORTS
    ok = True
    files = [
        "connector_certification_verdict.json",
        "connector_sdk_contract_report.json",
        "connector_certification_matrix.json",
        "unsafe_connector_negative_tests_report.json",
        "certified_connector_manifest.json",
        "connector_command_transcript.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "connector_certification_verdict.json")
    ok &= check_matrix_has_rows(d, "connector_certification_matrix.json")
    return ok


def validate_agent_catalog() -> bool:
    d = CATALOG_REPORTS
    ok = True
    files = [
        "agent_catalog_lifecycle_verdict.json",
        "agent_catalog_export.json",
        "agent_lifecycle_acceptance_matrix.json",
        "change_management_report.json",
        "agent_rollback_report.json",
        "emergency_suspend_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "agent_catalog_lifecycle_verdict.json")
    ok &= check_matrix_has_rows(d, "agent_lifecycle_acceptance_matrix.json")
    return ok


def validate_multi_agent() -> bool:
    d = MULTI_AGENT_REPORTS
    ok = True
    files = [
        "multi_agent_orchestration_verdict.json",
        "multi_agent_acceptance_matrix.json",
        "delegation_contract_report.json",
        "inter_agent_evidence_handoff_report.json",
        "multi_agent_negative_tests_report.json",
        "multi_agent_replay_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "multi_agent_orchestration_verdict.json")
    ok &= check_matrix_has_rows(d, "multi_agent_acceptance_matrix.json")
    return ok


def validate_auth_rbac() -> bool:
    d = AUTH_REPORTS
    ok = True
    files = [
        "auth_rbac_verdict.json",
        "auth_rbac_acceptance_matrix.json",
        "tenant_isolation_report.json",
        "permission_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "auth_rbac_verdict.json")
    ok &= check_matrix_has_rows(d, "auth_rbac_acceptance_matrix.json")
    return ok


def validate_data_governance() -> bool:
    d = DATA_GOV_REPORTS
    ok = True
    files = [
        "data_governance_verdict.json",
        "privacy_control_matrix.json",
        "retention_deletion_export_report.json",
        "legal_hold_report.json",
        "audit_export_report.json",
        "secret_redaction_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "data_governance_verdict.json")
    ok &= check_matrix_has_rows(d, "privacy_control_matrix.json")
    return ok


def validate_production_ops() -> bool:
    d = OPS_REPORTS
    ok = True
    files = [
        "production_ops_local_verdict.json",
        "bootstrap_install_report.json",
        "backup_restore_report.json",
        "rollback_recovery_report.json",
        "monitoring_observability_report.json",
        "incident_response_report.md",
        "cost_quota_budget_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "production_ops_local_verdict.json")
    return ok


def validate_domain_evals() -> bool:
    d = EVALS_REPORTS
    ok = True
    files = [
        "domain_eval_verdict.json",
        "domain_eval_matrix.json",
        "operator_dashboard_report.json",
        "review_queue_report.json",
        "human_review_criteria_report.md",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "domain_eval_verdict.json")
    ok &= check_matrix_has_rows(d, "domain_eval_matrix.json")
    return ok


def validate_security_review() -> bool:
    d = SECURITY_REVIEW_REPORTS
    ok = True
    files = [
        "security_review_verdict.json",
        "threat_model.md",
        "abuse_case_matrix.json",
        "security_negative_tests_report.json",
        "supply_chain_report.json",
        "enterprise_no_overclaim_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "security_review_verdict.json")
    ok &= check_matrix_has_rows(d, "abuse_case_matrix.json")
    return ok


def validate_control_plane() -> bool:
    d = CONTROL_PLANE_REPORTS
    ok = True
    files = [
        "control_plane_verdict.json",
        "control_plane_acceptance_matrix.json",
        "control_plane_api_schema_manifest.json",
        "control_plane_cli_transcript.json",
        "control_plane_audit_report.json",
        "control_plane_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "control_plane_verdict.json")
    ok &= check_matrix_has_rows(d, "control_plane_acceptance_matrix.json")
    return ok


def validate_durable_workers() -> bool:
    d = DURABLE_REPORTS
    ok = True
    files = [
        "durable_workers_verdict.json",
        "queue_scheduler_acceptance_matrix.json",
        "worker_resume_replay_report.json",
        "concurrency_isolation_report.json",
        "dead_letter_report.json",
        "worker_failure_injection_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "durable_workers_verdict.json")
    ok &= check_matrix_has_rows(d, "queue_scheduler_acceptance_matrix.json")
    return ok


def validate_process_intake() -> bool:
    d = PROCESS_INT_REPORTS
    ok = True
    files = [
        "process_intake_contract_compiler_verdict.json",
        "business_process_schema_manifest.json",
        "process_to_contract_diff_report.json",
        "business_kpi_mapping_report.json",
        "process_intake_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "process_intake_contract_compiler_verdict.json")
    return ok


def validate_risk_policy() -> bool:
    d = RISK_REPORTS
    ok = True
    files = [
        "risk_tier_policy_verdict.json",
        "risk_policy_matrix.json",
        "high_risk_review_report.json",
        "risk_escalation_report.json",
        "risk_policy_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "risk_tier_policy_verdict.json")
    ok &= check_matrix_has_rows(d, "risk_policy_matrix.json")
    return ok


def validate_enterprise_knowledge() -> bool:
    d = KNOWLEDGE_REPORTS
    ok = True
    files = [
        "enterprise_knowledge_rag_verdict.json",
        "knowledge_ingestion_manifest.json",
        "permission_aware_retrieval_report.json",
        "staleness_conflict_report.json",
        "citation_evidence_report.json",
        "memory_revocation_report.json",
        "rag_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "enterprise_knowledge_rag_verdict.json")
    return ok


def validate_packaging() -> bool:
    d = PACKAGING_REPORTS
    ok = True
    files = [
        "packaging_deployment_verdict.json",
        "deployment_manifest_report.json",
        "environment_profile_report.json",
        "migration_rollback_report.json",
        "bootstrap_healthcheck_transcript.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "packaging_deployment_verdict.json")
    return ok


def validate_live_connector() -> bool:
    d = LIVE_CONNECTOR_REPORTS
    ok = True
    files = [
        "live_connector_readiness_verdict.json",
        "live_connector_policy_matrix.json",
        "live_connector_dry_run_report.json",
        "live_connector_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "live_connector_readiness_verdict.json")
    ok &= check_matrix_has_rows(d, "live_connector_policy_matrix.json")
    return ok


def validate_performance_slo() -> bool:
    d = PERF_REPORTS
    ok = True
    files = [
        "performance_concurrency_slo_verdict.json",
        "performance_scenario_manifest.json",
        "concurrent_workflow_report.json",
        "resource_quota_report.json",
        "slo_threshold_report.json",
        "performance_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "performance_concurrency_slo_verdict.json")
    return ok


def validate_onboarding() -> bool:
    d = ONBOARDING_REPORTS
    ok = True
    files = [
        "onboarding_deployment_handoff_verdict.json",
        "NEW_COMPANY_ONBOARDING_RUNBOOK.md",
        "CONNECTOR_ONBOARDING_RUNBOOK.md",
        "WORKFLOW_PACK_AUTHORING_GUIDE.md",
        "OPERATOR_TRAINING_RUNBOOK.md",
        "LOCAL_TO_PRODUCTION_HANDOFF_GUIDE.md",
        "customer_uat_pack_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "onboarding_deployment_handoff_verdict.json")
    return ok


def validate_event_webhook() -> bool:
    d = LAST_MILE_REPORTS
    ok = True
    verdict_prefixes = [
        "event_webhook", "ui_rpa", "dlp", "approval", "template",
        "model", "schema", "upgrade", "dryrun", "policy_inheritance",
    ]
    for prefix in verdict_prefixes:
        ok &= check_exists(d / f"{prefix}_integration_verdict.json")
        ok &= check_verdict_pass(d, f"{prefix}_integration_verdict.json")
    additional = [
        "event_webhook_security_report.json",
        "ui_rpa_replay_report.json",
        "dlp_negative_tests_report.json",
        "approval_workflow_matrix.json",
        "template_instantiation_certification_report.json",
        "model_prompt_template_regression_report.json",
        "connector_schema_migration_report.json",
        "last_mile_acceptance_matrix.json",
        "last_mile_command_transcript.json",
    ]
    for f in additional:
        ok &= check_exists(d / f)
    ok &= check_matrix_has_rows(d, "approval_workflow_matrix.json")
    ok &= check_matrix_has_rows(d, "last_mile_acceptance_matrix.json")
    return ok


def validate_policy_pack() -> bool:
    d = FINAL_ADOPTION_REPORTS
    ok = True
    verdict_prefixes = [
        "policy_pack_regulatory_controls",
        "tamper_evident_audit_lineage",
        "credential_secret_lifecycle",
        "live_cutover_change_management",
        "enterprise_accountability_usage_governance",
        "outbound_communications_governance",
        "encryption_key_residency_boundary",
        "vendor_third_party_risk",
        "support_diagnostics_bundle",
        "admin_operability_proof",
    ]
    for prefix in verdict_prefixes:
        ok &= check_exists(d / f"{prefix}_verdict.json")
        ok &= check_verdict_pass(d, f"{prefix}_verdict.json")
    additional = [
        "policy_pack_matrix.json",
        "policy_conflict_resolution_report.json",
        "audit_lineage_report.json",
        "audit_tamper_negative_tests_report.json",
        "credential_scope_rotation_revocation_report.json",
        "live_cutover_dry_run_report.json",
        "usage_accountability_report.json",
        "outbound_communications_negative_tests_report.json",
        "data_residency_encryption_policy_report.json",
        "vendor_connector_risk_matrix.json",
        "redacted_support_bundle_manifest.json",
        "admin_operability_cli_api_transcript.json",
        "final_adoption_acceptance_matrix.json",
        "final_adoption_command_transcript.json",
    ]
    for f in additional:
        ok &= check_exists(d / f)
    ok &= check_matrix_has_rows(d, "policy_pack_matrix.json")
    ok &= check_matrix_has_rows(d, "vendor_connector_risk_matrix.json")
    ok &= check_matrix_has_rows(d, "final_adoption_acceptance_matrix.json")
    return ok


def validate_assurance_case() -> bool:
    d = ASSURANCE_REPORTS
    ok = True
    files = [
        "enterprise_assurance_case.json",
        "ENTERPRISE_ASSURANCE_CASE.md",
        "claim_evidence_traceability_matrix.json",
        "proof_quality_matrix.json",
        "stale_evidence_negative_tests_report.json",
        "assurance_case_verdict.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "assurance_case_verdict.json")
    ok &= check_matrix_has_rows(d, "claim_evidence_traceability_matrix.json")
    ok &= check_matrix_has_rows(d, "proof_quality_matrix.json")
    return ok


def validate_business_state() -> bool:
    d = BUSINESS_STATE_REPORTS
    ok = True
    files = [
        "business_state_ledger_verdict.json",
        "business_mutation_ledger.json",
        "reconciliation_report.json",
        "partial_failure_compensation_report.json",
        "duplicate_mutation_negative_tests_report.json",
        "manual_correction_audit_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "business_state_ledger_verdict.json")
    return ok


def validate_failover_drill() -> bool:
    d = FAILOVER_REPORTS
    ok = True
    files = [
        "failover_disaster_drill_verdict.json",
        "worker_crash_recovery_report.json",
        "queue_interruption_report.json",
        "storage_corruption_detection_report.json",
        "runtime_restart_recovery_report.json",
        "orphaned_state_scan_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "failover_disaster_drill_verdict.json")
    return ok


def validate_sandbox_live_boundary() -> bool:
    d = SANDBOX_LIVE_REPORTS
    ok = True
    files = [
        "sandbox_live_equivalence_verdict.json",
        "fake_connector_coverage_matrix.json",
        "live_revalidation_requirements.json",
        "local_vs_live_claim_boundary_report.md",
        "sandbox_live_no_overclaim_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "sandbox_live_equivalence_verdict.json")
    ok &= check_matrix_has_rows(d, "fake_connector_coverage_matrix.json")
    return ok


def validate_whole_company_exemplar() -> bool:
    d = WHOLE_COMPANY_REPORTS
    ok = True
    files = [
        "whole_company_workflow_verdict.json",
        "whole_company_process_intake.json",
        "whole_company_contract_bundle_manifest.json",
        "whole_company_multi_agent_trace.json",
        "whole_company_workflow_replay_report.json",
        "whole_company_reconciliation_report.json",
        "whole_company_uat_pack.md",
        "whole_company_support_bundle_manifest.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "whole_company_workflow_verdict.json")
    return ok


def validate_residual_risk() -> bool:
    d = RESIDUAL_RISK_REPORTS
    ok = True
    files = [
        "residual_risk_authority_verdict.json",
        "residual_risk_register.json",
        "deployment_authority_matrix.json",
        "activation_readiness_report.json",
        "residual_risk_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "residual_risk_authority_verdict.json")
    ok &= check_matrix_has_rows(d, "deployment_authority_matrix.json")
    return ok


def validate_customer_data_migration() -> bool:
    d = DATA_MIGRATION_REPORTS
    ok = True
    files = [
        "customer_data_migration_verdict.json",
        "import_export_manifest.json",
        "migration_schema_compatibility_report.json",
        "data_redaction_validation_report.json",
        "offboarding_export_report.json",
        "migration_replay_report.json",
        "customer_data_migration_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "customer_data_migration_verdict.json")
    return ok


def validate_operator_usability() -> bool:
    d = OPERATOR_USABILITY_REPORTS
    ok = True
    files = [
        "operator_usability_verdict.json",
        "operator_adoption_transcript.json",
        "operator_error_recovery_report.json",
        "operator_accessibility_check_report.json",
        "operator_help_and_docs_manifest.json",
        "operator_usability_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "operator_usability_verdict.json")
    return ok


def validate_identity_hardening() -> bool:
    d = IDENTITY_HARDENING_REPORTS
    ok = True
    files = [
        "identity_session_access_review_verdict.json",
        "mfa_readiness_report.json",
        "session_lifecycle_report.json",
        "access_review_report.json",
        "delegated_access_audit_report.json",
        "service_account_review_report.json",
        "identity_hardening_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "identity_session_access_review_verdict.json")
    return ok


def validate_api_abuse() -> bool:
    d = API_ABUSE_REPORTS
    ok = True
    files = [
        "api_abuse_rate_limit_verdict.json",
        "rate_limit_quota_report.json",
        "resource_isolation_report.json",
        "retry_storm_negative_tests_report.json",
        "tenant_fairness_report.json",
        "quota_exception_audit_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "api_abuse_rate_limit_verdict.json")
    return ok


def validate_cross_tenant() -> bool:
    d = CROSS_TENANT_REPORTS
    ok = True
    files = [
        "cross_tenant_leakage_verdict.json",
        "leakage_test_matrix.json",
        "restricted_value_scan_report.json",
        "concurrent_tenant_isolation_report.json",
        "cross_tenant_leakage_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "cross_tenant_leakage_verdict.json")
    ok &= check_matrix_has_rows(d, "leakage_test_matrix.json")
    return ok


def validate_audit_retention() -> bool:
    d = AUDIT_RETENTION_REPORTS
    ok = True
    files = [
        "audit_retention_ediscovery_verdict.json",
        "audit_retention_policy_report.json",
        "legal_hold_report.json",
        "ediscovery_search_report.json",
        "legal_export_bundle_manifest.json",
        "audit_retention_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "audit_retention_ediscovery_verdict.json")
    return ok


def validate_config_drift() -> bool:
    d = CONFIG_DRIFT_REPORTS
    ok = True
    files = [
        "config_drift_environment_promotion_verdict.json",
        "environment_profile_matrix.json",
        "config_drift_report.json",
        "environment_promotion_report.json",
        "environment_rollback_report.json",
        "config_drift_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "config_drift_environment_promotion_verdict.json")
    ok &= check_matrix_has_rows(d, "environment_profile_matrix.json")
    return ok


def validate_cutover_drill() -> bool:
    d = CUTOVER_REPORTS
    ok = True
    files = [
        "production_like_cutover_rollback_verdict.json",
        "canary_dry_run_report.json",
        "cutover_checklist_report.json",
        "post_cutover_verification_report.json",
        "emergency_rollback_report.json",
        "cutover_notification_manifest.json",
        "cutover_drill_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "production_like_cutover_rollback_verdict.json")
    return ok


# ----- targets sharing ENTERPRISE_ADOPTION_REPORTS -----

def validate_sso_idp() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "sso_idp_lifecycle_verdict.json",
        "sso_scim_provisioning_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "sso_idp_lifecycle_verdict.json")
    return ok


def validate_sbom() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "sbom_vulnerability_license_verdict.json",
        "sbom_report.json",
        "dependency_vulnerability_scan_report.json",
        "license_policy_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "sbom_vulnerability_license_verdict.json")
    return ok


def validate_segregation_duties() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "segregation_of_duties_verdict.json",
        "dual_control_approval_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "segregation_of_duties_verdict.json")
    return ok


def validate_field_record_authz() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "field_record_authorization_verdict.json",
        "field_record_authz_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "field_record_authorization_verdict.json")
    return ok


def validate_backup_restore() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "backup_restore_rpo_rto_verdict.json",
        "point_in_time_restore_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "backup_restore_rpo_rto_verdict.json")
    return ok


def validate_customer_acceptance() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "customer_acceptance_uat_signoff_verdict.json",
        "uat_rework_go_no_go_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "customer_acceptance_uat_signoff_verdict.json")
    return ok


def validate_data_quality() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "data_quality_source_trust_verdict.json",
        "source_trust_negative_tests_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "data_quality_source_trust_verdict.json")
    return ok


def validate_training_runbook() -> bool:
    d = ENTERPRISE_ADOPTION_REPORTS
    ok = True
    files = [
        "training_runbook_change_adoption_verdict.json",
        "operator_business_user_handoff_pack.md",
    ]
    for f in files:
        ok &= check_exists(d / f)
    ok &= check_verdict_pass(d, "training_runbook_change_adoption_verdict.json")
    return ok


# ----- special targets -----

def validate_enterprise_ready() -> bool:
    d = ENTERPRISE_REPORTS
    ok = True
    files = [
        "enterprise_ready_verdict.json",
        "ENTERPRISE_READY_VERDICT.md",
        "enterprise_acceptance_matrix.json",
        "enterprise_gap_register.json",
        "ENTERPRISE_GAP_REGISTER.md",
        "enterprise_gap_closure_report.json",
        "ENTERPRISE_GAP_CLOSURE_REPORT.md",
        "enterprise_evidence_manifest.json",
        "enterprise_command_transcript.json",
        "enterprise_no_overclaim_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)

    v = d / "enterprise_ready_verdict.json"
    if v.exists():
        data = load_json(v)
        ok &= check_eq(data, "verdict", "PASS")
        for gate in ALL_ENTERPRISE_GATES:
            gate_val = data.get(gate)
            ok &= check_eq(data, gate, "PASS")

        # Provenance check: verify that gates backed by individual targets
        # have a corresponding verdict file in the target's report directory
        gate_to_dir = {
            "enterprise_contract_system": CONTRACT_REPORTS,
            "enterprise_adapter_sandbox": ADAPTER_REPORTS,
            "company_workflow_pack": WORKFLOW_REPORTS,
            "enterprise_workflow_runtime": RUNTIME_REPORTS,
            "arbitrary_compliant_agent_generation": GENERATION_REPORTS,
            "connector_sdk_certification": CONNECTOR_REPORTS,
            "agent_catalog_lifecycle": CATALOG_REPORTS,
            "multi_agent_orchestration": MULTI_AGENT_REPORTS,
            "auth_rbac_tenant_isolation": AUTH_REPORTS,
            "data_governance_compliance": DATA_GOV_REPORTS,
            "production_ops_local": OPS_REPORTS,
            "domain_evals_dashboard": EVALS_REPORTS,
            "enterprise_onboarding_deployment_handoff": ONBOARDING_REPORTS,
            "enterprise_control_plane_api": CONTROL_PLANE_REPORTS,
            "durable_workflow_workers": DURABLE_REPORTS,
            "business_process_intake_contract_compiler": PROCESS_INT_REPORTS,
            "risk_tiered_automation_policy": RISK_REPORTS,
            "enterprise_knowledge_rag_governance": KNOWLEDGE_REPORTS,
            "packaging_deployment_artifacts": PACKAGING_REPORTS,
            "live_connector_readiness_boundary": LIVE_CONNECTOR_REPORTS,
            "performance_concurrency_slo_local": PERF_REPORTS,
            "event_webhook_integration": LAST_MILE_REPORTS,
            "ui_rpa_automation_sandbox": LAST_MILE_REPORTS,
            "dlp_data_classification_egress": LAST_MILE_REPORTS,
            "approval_escalation_delegation": LAST_MILE_REPORTS,
            "agent_template_pack_registry": LAST_MILE_REPORTS,
            "model_version_eval_governance": LAST_MILE_REPORTS,
            "connector_schema_compatibility": LAST_MILE_REPORTS,
            "upgrade_supportability_local": LAST_MILE_REPORTS,
            "customer_deployment_dry_run": LAST_MILE_REPORTS,
            "org_policy_inheritance": LAST_MILE_REPORTS,
            "policy_pack_regulatory_controls": FINAL_ADOPTION_REPORTS,
            "tamper_evident_audit_lineage": FINAL_ADOPTION_REPORTS,
            "credential_secret_lifecycle": FINAL_ADOPTION_REPORTS,
            "live_cutover_change_management": FINAL_ADOPTION_REPORTS,
            "enterprise_accountability_usage_governance": FINAL_ADOPTION_REPORTS,
            "outbound_communications_governance": FINAL_ADOPTION_REPORTS,
            "encryption_key_residency_boundary": FINAL_ADOPTION_REPORTS,
            "vendor_third_party_risk_local": FINAL_ADOPTION_REPORTS,
            "support_diagnostics_bundle": FINAL_ADOPTION_REPORTS,
            "admin_operability_proof": FINAL_ADOPTION_REPORTS,
            "enterprise_assurance_case_traceability": ASSURANCE_REPORTS,
            "business_state_ledger_reconciliation": BUSINESS_STATE_REPORTS,
            "local_failover_disaster_drill": FAILOVER_REPORTS,
            "sandbox_to_live_equivalence_boundary": SANDBOX_LIVE_REPORTS,
            "whole_company_workflow_exemplar": WHOLE_COMPANY_REPORTS,
            "residual_risk_deployment_authority": RESIDUAL_RISK_REPORTS,
            "customer_data_migration_import_export": DATA_MIGRATION_REPORTS,
            "operator_usability_accessibility_error_recovery": OPERATOR_USABILITY_REPORTS,
            "enterprise_identity_session_access_review": IDENTITY_HARDENING_REPORTS,
            "api_abuse_rate_limit_resource_isolation": API_ABUSE_REPORTS,
            "cross_tenant_leakage_penetration_local": CROSS_TENANT_REPORTS,
            "audit_retention_ediscovery": AUDIT_RETENTION_REPORTS,
            "config_drift_environment_promotion": CONFIG_DRIFT_REPORTS,
            "production_like_cutover_rollback_drill": CUTOVER_REPORTS,
            "enterprise_sso_idp_lifecycle": ENTERPRISE_ADOPTION_REPORTS,
            "sbom_vulnerability_license_local": ENTERPRISE_ADOPTION_REPORTS,
            "segregation_of_duties_dual_control": ENTERPRISE_ADOPTION_REPORTS,
            "field_record_authorization": ENTERPRISE_ADOPTION_REPORTS,
            "backup_restore_rpo_rto_local": ENTERPRISE_ADOPTION_REPORTS,
            "customer_acceptance_uat_signoff": ENTERPRISE_ADOPTION_REPORTS,
            "data_quality_source_trust": ENTERPRISE_ADOPTION_REPORTS,
            "training_runbook_change_adoption": ENTERPRISE_ADOPTION_REPORTS,
            "enterprise_security_review_local": SECURITY_REVIEW_REPORTS,
        }
        for gate, gate_dir in gate_to_dir.items():
            if not gate_dir.exists() or not any(gate_dir.iterdir()):
                print(f"  FAIL  {gate}: no individual target evidence in {gate_dir}")
                ok = False
            else:
                print(f"  PASS  {gate}: individual evidence present in {gate_dir}")

        # Check no_overclaim field
        no_oc = data.get("no_overclaim")
        if no_oc == "PASS":
            print(f"  PASS  no_overclaim = PASS")
        elif no_oc is True:
            print(f"  FAIL  no_overclaim is boolean True, should be string 'PASS'")
            ok = False

    gap = d / "enterprise_gap_register.json"
    if gap.exists():
        data = load_json(gap)
        rows = data.get("rows", [])
        row_map = {r.get("ent_id"): r for r in rows}
        for ent_id in ALL_ENT_ROWS:
            row = row_map.get(ent_id)
            if row is None:
                print(f"  FAIL  {ent_id} missing from gap register")
                ok = False
            elif row.get("status") != "CLOSED":
                print(f"  FAIL  {ent_id} status is {row.get('status')!r} (expected CLOSED)")
                ok = False
            else:
                print(f"  PASS  {ent_id} status CLOSED")

    m = d / "enterprise_acceptance_matrix.json"
    if m.exists():
        ok &= check_has(load_json(m), "rows")

    # Verify no_overclaim report exists and says PASS
    noc = d / "enterprise_no_overclaim_report.json"
    if noc.exists():
        noc_data = load_json(noc)
        if noc_data.get("status") != "PASS":
            print(f"  FAIL  no_overclaim_report status is not PASS")
            ok = False
        else:
            print(f"  PASS  no_overclaim_report status PASS")

    return ok


def validate_enterprise_final() -> bool:
    d = ENTERPRISE_FINAL
    ok = True
    files = [
        "final_enterprise_closure_verdict.json",
        "FUNCTIONAL_ENTERPRISE_AGENT_FACTORY_PLATFORM_VERDICT.md",
        "local_ci_evidence_report.json",
        "LOCAL_CI_EVIDENCE_REPORT.md",
        "enterprise_local_final_harness_report.json",
        "ENTERPRISE_LOCAL_FINAL_HARNESS_REPORT.md",
        "enterprise_clean_checkout_report.json",
        "ENTERPRISE_CLEAN_CHECKOUT_REPORT.md",
        "enterprise_first_run_manifest.json",
        "enterprise_second_run_manifest.json",
        "enterprise_idempotency_report.json",
        "ENTERPRISE_IDEMPOTENCY_REPORT.md",
        "enterprise_idempotency_diff_report.json",
        "enterprise_final_report_bundle_manifest.json",
        "ENTERPRISE_FINAL_REPORT_BUNDLE.md",
        "no_overclaim_report.json",
    ]
    for f in files:
        ok &= check_exists(d / f)

    v = d / "final_enterprise_closure_verdict.json"
    if v.exists():
        data = load_json(v)
        ok &= check_eq(data, "verdict", "PASS")
        ok &= check_has(data, "classification")
        ok &= check_has(data, "final_sha")
        ok &= check_has(data, "baseline_sha")
        ok &= check_eq(data, "proof_scope", "ENTERPRISE_LOCAL_FINAL_CLOSURE")
        ok &= check_has(data, "no_overclaim")
        ok &= check_has(data, "core_local_final")
        ok &= check_has(data, "enterprise_ready")
        ok &= check_has(data, "enterprise_local_final_harness")
        ok &= check_has(data, "clean_checkout")
        ok &= check_has(data, "idempotency")
        ok &= check_has(data, "final_report_bundle")
        ok &= check_has(data, "enterprise_gap_closure_ent_001_through_ent_084")
        ok &= check_has(data, "local_ci_mode")
        ok &= check_has(data, "live_network_required")
        ok &= check_has(data, "live_provider_required")
        ok &= check_has(data, "real_external_saas_required")
        ok &= check_has(data, "proof_scope")

    ci = d / "local_ci_evidence_report.json"
    if ci.exists():
        ok &= check_eq(load_json(ci), "ci_mode", "LOCAL_ONLY")

    # Validate idempotency report uses real hashes
    idem = d / "enterprise_idempotency_report.json"
    if idem.exists():
        idem_data = load_json(idem)
        first_sha = idem_data.get("first_run_sha", "")
        second_sha = idem_data.get("second_run_sha", "")
        if first_sha in ("abc123", "FIRST_RUN_NOT_FOUND", ""):
            print(f"  FAIL  idempotency first_run_sha is fake/missing: {first_sha!r}")
            ok = False
        else:
            print(f"  PASS  idempotency first_run_sha = {first_sha}")
        if second_sha in ("abc123", "SECOND_RUN_NOT_FOUND", ""):
            print(f"  FAIL  idempotency second_run_sha is fake/missing: {second_sha!r}")
            ok = False
        else:
            print(f"  PASS  idempotency second_run_sha = {second_sha}")
        if first_sha != second_sha and first_sha not in ("abc123", "FIRST_RUN_NOT_FOUND"):
            print(f"  FAIL  idempotency mismatch: first/second run differ")
            ok = False
        else:
            print(f"  PASS  idempotency: runs match")

    # Validate clean checkout report
    cc = d / "enterprise_clean_checkout_report.json"
    if cc.exists():
        cc_data = load_json(cc)
        if cc_data.get("clean_checkout") is not True:
            print(f"  FAIL  clean_checkout is not True")
            ok = False
        else:
            print(f"  PASS  clean_checkout confirmed")

    return ok


# ---------------------------------------------------------------------------
# Target dispatch
# ---------------------------------------------------------------------------

VALIDATORS: dict[str, callable] = {
    "contract-system": validate_contract_system,
    "adapter-sandbox": validate_adapter_sandbox,
    "workflow-pack": validate_workflow_pack,
    "workflow-runtime": validate_workflow_runtime,
    "arbitrary-agent-generation": validate_arbitrary_agent_generation,
    "connector-certification": validate_connector_certification,
    "agent-catalog": validate_agent_catalog,
    "multi-agent": validate_multi_agent,
    "auth-rbac": validate_auth_rbac,
    "data-governance": validate_data_governance,
    "production-ops": validate_production_ops,
    "domain-evals": validate_domain_evals,
    "security-review": validate_security_review,
    "control-plane": validate_control_plane,
    "durable-workers": validate_durable_workers,
    "process-intake": validate_process_intake,
    "risk-policy": validate_risk_policy,
    "enterprise-knowledge": validate_enterprise_knowledge,
    "packaging": validate_packaging,
    "live-connector": validate_live_connector,
    "performance-slo": validate_performance_slo,
    "onboarding": validate_onboarding,
    "event-webhook": validate_event_webhook,
    "policy-pack": validate_policy_pack,
    "assurance-case": validate_assurance_case,
    "business-state": validate_business_state,
    "failover-drill": validate_failover_drill,
    "sandbox-live-boundary": validate_sandbox_live_boundary,
    "whole-company-exemplar": validate_whole_company_exemplar,
    "residual-risk": validate_residual_risk,
    "customer-data-migration": validate_customer_data_migration,
    "operator-usability": validate_operator_usability,
    "identity-hardening": validate_identity_hardening,
    "api-abuse": validate_api_abuse,
    "cross-tenant": validate_cross_tenant,
    "audit-retention": validate_audit_retention,
    "config-drift": validate_config_drift,
    "cutover-drill": validate_cutover_drill,
    "sso-idp": validate_sso_idp,
    "sbom": validate_sbom,
    "segregation-duties": validate_segregation_duties,
    "field-record-authz": validate_field_record_authz,
    "backup-restore": validate_backup_restore,
    "customer-acceptance": validate_customer_acceptance,
    "data-quality": validate_data_quality,
    "training-runbook": validate_training_runbook,
    "enterprise-ready": validate_enterprise_ready,
    "enterprise-final": validate_enterprise_final,
}

ALL_TARGETS = sorted(VALIDATORS.keys())


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(f"Usage: {sys.argv[0]} <target>")
        print(f"       {sys.argv[0]} --list")
        print(f"\nAvailable targets ({len(ALL_TARGETS)}):")
        for t in ALL_TARGETS:
            print(f"  {t}")
        sys.exit(0 if "--list" in sys.argv else 1)

    target = sys.argv[1]
    if target == "--list":
        for t in ALL_TARGETS:
            print(t)
        sys.exit(0)

    if target not in VALIDATORS:
        print(f"Unknown target: {target}")
        print(f"Use --list to see available targets")
        sys.exit(1)

    result = VALIDATORS[target]()
    status = "PASS" if result else "FAIL"
    print(f"=== {target} validation: {status} ===")
    sys.exit(0 if result else 1)


if __name__ == "__main__":
    main()
